#!/usr/bin/python
import Adafruit_BBIO.UART as uart
import serial
from time import strftime as time
import json 
import pycurl

uart.setup("UART1")
ser=serial.Serial(port = "/dev/ttyO1", baudrate=9600)

ser.close()
ser.open()

TIME_MINUTES_TENS = [ '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
TIME_MINUTES_ONES = [ ')', '!', '@', '#', '$', '%', '^', '&', '*', '(']
TIME_HOURS_TENS   = [ 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't']
TIME_HOURS_ONES   = [ 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T']

time_Minutes = TIME_MINUTES_ONES[ int(time("%M")) %10] + \
    TIME_MINUTES_TENS[int(time("%M")) / 10]
time_Hours = TIME_HOURS_ONES[ int(time("%H")) %10] + \
    TIME_HOURS_TENS[int(time("%H")) / 10]

if ser.isOpen():
    '''
    print time("%M")
    print time("%H")
    print time_Minutes
    print time_Hours
    '''
    ser.write(time_Minutes + time_Hours)
    ser.close()
