#!/usr/bin/python

import Adafruit_BBIO.UART as uart
import serial
from time import sleep
from time import strftime as time
import subprocess

uart.setup("UART2")
ser=serial.Serial(port = "/dev/ttyO2", baudrate=9600)

ser.close()
ser.open()

WATER_STORED        = [ 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's']
WATER_USED          = [ 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S']
ENERGY_STORED       = [ 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
ENERGY_USED         = [ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

i = 0
sendEnergyStored = 0
sendEnergyUsed = 0

#while True:
for x in range(0,10):
    i = i+1
    if (i % 137 == 0):
        sendEnergyStored = sendEnergyStored + 1
        if sendEnergyStored > 8:
            sendEnergyStored = 0

    if (i % 571 == 0):
        sendEnergyUsed = sendEnergyUsed + 1
        if sendEnergyUsed > 8:
            sendEnergyUsed = 0

    if (i == 1000000):
        i = 0

    print ENERGY_STORED[sendEnergyStored] + ENERGY_USED[sendEnergyUsed]
    print WATER_STORED[sendEnergyStored] + WATER_USED[sendEnergyUsed]
    if(ser.isOpen()):
        ser.write(ENERGY_STORED[sendEnergyStored] + ENERGY_USED[sendEnergyUsed])
        ser.write(WATER_STORED[sendEnergyStored] + WATER_USED[sendEnergyUsed])
        ser.close()
